# Generated by Django 4.2.8 on 2024-10-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_admin_id_alter_attendance_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationstudent',
            name='student',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fcm_token',
        ),
        migrations.DeleteModel(
            name='NotificationStaff',
        ),
        migrations.DeleteModel(
            name='NotificationStudent',
        ),
    ]
